spring:
  application:
    name: Shrimali
    version: 1.0.0

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${PG_DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      pool-name: HikariPool
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # --- ORM (Hibernate/JPA) ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        generate_statistics: false
        jdbc:
          batch_size: 1000

  security:
    debug: false
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: "https://www.shrimalis.com/login/oauth2/code/google"
#            redirect-uri: "https://dyivpjehgjmg8.cloudfront.net/login/oauth2/code/google"
        provider:
          google:
            user-name-attribute: sub
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            token-uri: https://oauth2.googleapis.com/token

  # --- FILE UPLOADS ---
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    error:
      include-message: never

server:
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 3005

logging:
  level:
    reactor.netty: WARN
    org.springframework.security: WARN
    org.springframework.web: WARN
      # This silences the specific "Database info" block you shared
    org.hibernate.orm.connections.pooling: WARN
      # This silences the general Hibernate startup banner/metadata
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: WARN

app:
  env: prod

  # FRONTEND URL (React app)
  client:
    url: https://www.shrimalis.com
#    url: "https://dyivpjehgjmg8.cloudfront.net"

  cookie:
    http-only: true
    secure: true
    sameSite: Lax
    domain: ""
    forceSecure: true

  backup:
    bin-path: "C:/Program Files/PostgreSQL/17/bin/pg_dump.exe"
    cron: "0 0 */1 * * ?"
    path: "./backups/"
    database: ${PG_DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  admins:
    - pradipnsharma@gmail.com
    - abdul.khan@actionabl.ai
    - mahendra.bohra1974@gmail.com
    - narendrarajbohra@gmail.com
  super-admins:
    - shrimali.shvbadi@gmail.com
    - abdulrehman1793@gmail.com

aws:
  s3:
    bucket: shrimali-profile-images
